name: Run Pytest on Push

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ToDo_App/requirements.txt

    - name: Run tests with pytest
      run: |
        pytest ToDo_App/tests/tests_todo_app.py --maxfail=1 --disable-warnings -v
    - name: Install coverage tools
      run: pip install pytest-cov
#    - name: Run tests with coverage
#      run: pytest --cov=your_module tests/

